# Generated by Django 4.1.1 on 2022-10-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='micro_images',
            new_name='m_image1',
        ),
        migrations.AddField(
            model_name='service',
            name='m_image2',
            field=models.FileField(blank=True, null=True, upload_to='service'),
        ),
        migrations.AddField(
            model_name='service',
            name='m_image3',
            field=models.FileField(blank=True, null=True, upload_to='service'),
        ),
    ]
