# Generated by Django 4.1.1 on 2022-10-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_rename_micro_images_service_m_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='title',
            new_name='first_part_title',
        ),
        migrations.RenameField(
            model_name='mainslider',
            old_name='title',
            new_name='first_part_title',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='first_part_title',
        ),
        migrations.AddField(
            model_name='about',
            name='second_part_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='second_part_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='second_part_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
