# Generated by Django 4.1.1 on 2022-10-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_rename_title_about_first_part_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='m_image1',
            field=models.FileField(null=True, upload_to='service/m'),
        ),
        migrations.AlterField(
            model_name='service',
            name='m_image2',
            field=models.FileField(null=True, upload_to='service/m'),
        ),
        migrations.AlterField(
            model_name='service',
            name='m_image3',
            field=models.FileField(null=True, upload_to='service/m'),
        ),
    ]
