# Generated by Django 4.1.1 on 2022-10-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_service_m_image1_alter_service_m_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainslider',
            old_name='second_part_title',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='mainslider',
            old_name='first_part_title',
            new_name='title',
        ),
    ]
