# Generated by Django 4.1.1 on 2022-10-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_rename_second_part_title_mainslider_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
