# Generated by Django 4.1.1 on 2022-10-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_service_m_image1_word1_service_m_image1_word2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='year',
            field=models.CharField(default='', max_length=200),
        ),
    ]
