# Generated by Django 4.1.1 on 2022-11-13 11:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_roadmap_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslider',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
