# Generated by Django 4.1.1 on 2022-11-13 11:15

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_alter_mainslider_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslider',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
